### ISSUE TITLE
Shorthand for selecting distinct graphs in SPARQL

### ISSUE THREAD

**Issue by ktk** [w3c/sparql-dev#205]
## Why?

Selecting distinct graphs in SPARQL is a common requirement but often runs into performance issues with large datasets. Improving this query pattern could enhance usability and efficiency across implementations.

## Previous work

The SPARQL 1.1 way to do it is:

```sparql
SELECT DISTINCT ?g WHERE {
  GRAPH ?g { ?s ?p ?o}
} 
```

Which is very fast in some stores and not in others.

Stardog supports a short form for selecting graphs:  

 ```sparql
  SELECT * WHERE {
    GRAPH ?g {}
  } 
 ```
 
I like this because it omits the triples in the query, which are never wanted in the SPARQL 1.1 way of writing it.

## Proposed solution

Introduce optimized handling for graph selection queries, specifically targeting `SELECT DISTINCT ?g` patterns. A possible extension could support the Stardog-style shorthand.

## Considerations for backward compatibility

No major backward compatibility concerns if implemented as an optimization or optional feature. The Stardog shorthand would be a non-breaking addition if treated as syntactic sugar.

**Comment by afs** [comment]
The `GRAPH ?g {}` form is [standard SPARQL](https://www.w3.org/TR/sparql12-query/#defn_evalGraph).

Join the graph names with the eval of the empty pattern (the join identity, one row, no column). 

The quad form is not the way to do it!

**Comment by Tpt** [comment]
+1 to @afs (just realized that Oxigraph is not supporting it properly, adding a test in the testsuite would be great).

I am not sure an other dedicated syntax for this is a good idea, matching for the existing syntax to trigger a specific code path does not seems to be way more work than handling a new syntax.

**Comment by ktk** [comment]
Oh wow I did not realize that, thanks for the notice. Then I agree with @Tpt, a test-case would be great. Should I close the issue?

**Comment by afs** [comment]
> Oh wow I did not realize that, thanks for the notice. Then I agree with @Tpt, a test-case would be great. Should I close the issue?

Yes, please.
